name: Deploy automatizado do backend (develop)

on:
  push:
    branches:
      - develop
      
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: "Baixar c√≥digo"
      uses: actions/checkout@v4

    - name: Deploy via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
          username: ${{ secrets.FTP_USER }}
          server: '${{ secrets.FTP_HOST }}'
          ssh_private_key: ${{ secrets.SSH_KEY }}
          local_path: './*'
          remote_path: '/home/projects/tonsus-back-dev'
          sftpArgs: '-o ConnectTimeout=5'
          port: 22

    - name: Executar comandos na VPS
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: '${{ secrets.FTP_HOST }}'
        username: ${{ secrets.FTP_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
            cd /home/projects/tonsus-back-dev
            docker-compose up --build -d
